// <auto-generated />
using System;
using JobTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JobTrackerDbContext))]
    [Migration("20260726213401_AddTailoredCvPdf")]
    partial class AddTailoredCvPdf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobTracker.Domain.Entities.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("JobUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("job_url");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_job_applications_updated_at");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_job_applications_user_id_status");

                    b.ToTable("job_applications", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_applications_status", "status IN ('Applied', 'Interviewing', 'Offer', 'Rejected')");
                        });
                });

            modelBuilder.Entity("JobTracker.Domain.Entities.MasterCv", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_master_cvs_user_id_name");

                    b.ToTable("master_cvs", (string)null);
                });

            modelBuilder.Entity("JobTracker.Domain.Entities.TailoredCv", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AtsMatchScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ats_match_score");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_application_id");

                    b.Property<Guid>("MasterCvId")
                        .HasColumnType("uuid")
                        .HasColumnName("master_cv_id");

                    b.Property<string[]>("MissingKeywords")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("missing_keywords");

                    b.Property<byte[]>("PdfContent")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("pdf_content");

                    b.Property<string>("PdfFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pdf_file_name");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId")
                        .HasDatabaseName("ix_tailored_cvs_job_application_id");

                    b.HasIndex("MasterCvId")
                        .HasDatabaseName("ix_tailored_cvs_master_cv_id");

                    b.ToTable("tailored_cvs", null, t =>
                        {
                            t.HasCheckConstraint("ck_tailored_cvs_ats_match_score", "ats_match_score >= 0 AND ats_match_score <= 100");
                        });
                });

            modelBuilder.Entity("JobTracker.Domain.Entities.TailoredCv", b =>
                {
                    b.HasOne("JobTracker.Domain.Entities.JobApplication", "JobApplication")
                        .WithMany("TailoredCvs")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobTracker.Domain.Entities.MasterCv", "MasterCv")
                        .WithMany("TailoredCvs")
                        .HasForeignKey("MasterCvId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobApplication");

                    b.Navigation("MasterCv");
                });

            modelBuilder.Entity("JobTracker.Domain.Entities.JobApplication", b =>
                {
                    b.Navigation("TailoredCvs");
                });

            modelBuilder.Entity("JobTracker.Domain.Entities.MasterCv", b =>
                {
                    b.Navigation("TailoredCvs");
                });
#pragma warning restore 612, 618
        }
    }
}
